module.exports = {
  // Masters
  M_MEMBERS: 'M_MEMBERS',
  M_CHITS: 'M_CHITS',                    // was M_CHITS_GROUP
  M_CHIT_CONFIG: 'M_CHIT_CONFIG',
  M_ENROLLMENTS: 'M_ENROLLMENTS',        // was M_ENROLLMENT
  M_UPCOMING: 'M_UPCOMING',              // was M_UPCOMING_CHIT
  M_SELF_CHITS: 'M_SELF_CHITS',
  M_AGENT_TARGETS: 'M_AGENT_TARGETS',
  M_AGENT_TRANSFER: 'M_AGENT_TRANSFER',
  M_SUIT_FILE: 'M_SUIT_FILE',
  M_ACC_GROUPS: 'M_ACC_GROUPS',
  M_ACCOUNTS: 'M_ACCOUNTS',
  M_OPENING_BAL: 'M_OPENING_BAL',
  M_ACC_TREE: 'M_ACC_TREE',
  M_DISTRICTS: 'M_DISTRICTS',            // was M_DISTRICT
  M_CITIES: 'M_CITIES',                  // was M_CITY
  M_ROUTES: 'M_ROUTES',                  // was M_ROUTE
  M_AREAS: 'M_AREAS',                    // was M_AREA

  // Transactions
  T_AUCTIONS: 'T_AUCTIONS',
  T_AGENT_SETUP: 'T_AGENT_SETUP',
  T_COLLECTION_VERIFY: 'T_COLLECTION_VERIFY',

  // Utilities
  U_CONTACT_US: 'U_CONTACT_US',
  U_FAQ: 'U_FAQ',
  U_TERMS_PRIVACY: 'U_TERMS_PRIVACY',

  // System
  S_ROLES: 'S_ROLES',
  S_USERS: 'S_USERS'
};
