module.exports = {
  // Masters
  M_MEMBERS: 'M_MEMBERS',
  M_COMPANY: 'M_COMPANY',
  M_ROUTE: 'M_ROUTE',
  M_AREA: 'M_AREA',
  M_CHITS_GROUP: 'M_CHITS_GROUP',
  M_COUNTRY: 'M_COUNTRY',
  M_STATE: 'M_STATE',
  M_DISTRICT: 'M_DISTRICT',
  M_CITY: 'M_CITY',
  M_ENROLLMENT: 'M_ENROLLMENT',
  M_UPCOMING_CHIT: 'M_UPCOMING_CHIT',
  M_SUIT_FILE: 'M_SUIT_FILE',
  
  // Transactions
  T_AUCTIONS: 'T_AUCTIONS',
  T_AGENT_SETUP: 'T_AGENT_SETUP',
  T_COLLECTION_VERIFY: 'T_COLLECTION_VERIFY',
  
  // Utilities
  U_CONTACT_US: 'U_CONTACT_US',
  U_FAQ: 'U_FAQ',
  U_TERMS_PRIVACY: 'U_TERMS_PRIVACY',
};
