require('dotenv').config();
const app = require('./app');
const { sequelize } = require('./models'); // Will be generated by sequelize init

const PORT = process.env.PORT || 5000;

const startServer = async () => {
  try {
    // Authenticate with the database
    await sequelize.authenticate();
    console.log('Database connection has been established successfully.');

    // Start the server
    app.listen(PORT, () => {
      console.log(`Server is running on port ${PORT}.`);
    });
  } catch (error) {
    console.error('Unable to connect to the database:', error);
  }
};

startServer();
